#!/usr/bin/env node
// scripts/configure.mjs — write extension/config.js from flags or environment variables.
// Run ONCE by the publisher; end users never see or edit any of this.
//
//   node scripts/configure.mjs \
//        --github-client-id    Ov23liAbCdEf \
//        --token-exchange-url  https://colabhub-auth.<you>.workers.dev \
//        --google-client-id    1234-abc.apps.googleusercontent.com
//        [--github-auth-method oauth|device] [--google-auth-method webflow|chrome]
//        [--github-client-secret <40 hex>]   (dev/personal builds only — never for distribution)
//
// Env fallbacks: GITHUB_CLIENT_ID, TOKEN_EXCHANGE_URL, GITHUB_CLIENT_SECRET, GITHUB_AUTH_METHOD,
//                GOOGLE_CLIENT_ID, GOOGLE_AUTH_METHOD

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, arr) => {
    if (a.startsWith('--')) acc.push([a.slice(2), arr[i + 1] !== undefined && !arr[i + 1].startsWith('--') ? arr[i + 1] : 'true']);
    return acc;
  }, []),
);

const cfg = {
  GITHUB_CLIENT_ID: args['github-client-id'] ?? process.env.GITHUB_CLIENT_ID ?? '',
  GITHUB_CLIENT_SECRET: args['github-client-secret'] ?? process.env.GITHUB_CLIENT_SECRET ?? '',
  GITHUB_AUTH_METHOD: args['github-auth-method'] ?? process.env.GITHUB_AUTH_METHOD ?? 'oauth',
  TOKEN_EXCHANGE_URL: args['token-exchange-url'] ?? process.env.TOKEN_EXCHANGE_URL ?? '',
  GOOGLE_CLIENT_ID: args['google-client-id'] ?? process.env.GOOGLE_CLIENT_ID ?? '',
  GOOGLE_AUTH_METHOD: args['google-auth-method'] ?? process.env.GOOGLE_AUTH_METHOD ?? 'webflow',
};

if (!['oauth', 'device'].includes(cfg.GITHUB_AUTH_METHOD)) {
  console.error('GITHUB_AUTH_METHOD must be "oauth" (PKCE, default) or "device"');
  process.exit(1);
}
if (!['webflow', 'chrome'].includes(cfg.GOOGLE_AUTH_METHOD)) {
  console.error('GOOGLE_AUTH_METHOD must be "webflow" or "chrome"');
  process.exit(1);
}

if (cfg.TOKEN_EXCHANGE_URL && !/^https?:\/\/[^\s/]+/.test(cfg.TOKEN_EXCHANGE_URL)) {
  console.error('TOKEN_EXCHANGE_URL must be a full URL, e.g. https://colabhub-auth.<you>.workers.dev');
  process.exit(1);
}
cfg.TOKEN_EXCHANGE_URL = cfg.TOKEN_EXCHANGE_URL.replace(/\/+$/, '');
if (cfg.GITHUB_CLIENT_SECRET && !/^[a-f0-9]{40}$/i.test(cfg.GITHUB_CLIENT_SECRET)) {
  console.error('GITHUB_CLIENT_SECRET should be the 40-hex client secret from the OAuth App page');
  process.exit(1);
}

const out = `// config.js — GENERATED by scripts/configure.mjs. Re-run it to change values.
// See README.md → "Publisher setup" for where each value comes from.
export const CONFIG = Object.freeze({
  GITHUB_CLIENT_ID: ${JSON.stringify(cfg.GITHUB_CLIENT_ID)},
  TOKEN_EXCHANGE_URL: ${JSON.stringify(cfg.TOKEN_EXCHANGE_URL)},
  GITHUB_CLIENT_SECRET: ${JSON.stringify(cfg.GITHUB_CLIENT_SECRET)},
  GITHUB_AUTH_METHOD: ${JSON.stringify(cfg.GITHUB_AUTH_METHOD)},
  GOOGLE_CLIENT_ID: ${JSON.stringify(cfg.GOOGLE_CLIENT_ID)},
  GOOGLE_AUTH_METHOD: ${JSON.stringify(cfg.GOOGLE_AUTH_METHOD)},

  GITHUB_SCOPES: 'repo read:org',
  DRIVE_SCOPE: 'https://www.googleapis.com/auth/drive.readonly',
});
`;
fs.writeFileSync(path.join(root, 'extension', 'config.js'), out);

// When using chrome.identity.getAuthToken, the manifest needs an oauth2 block.
const manifestPath = path.join(root, 'extension', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
if (cfg.GOOGLE_AUTH_METHOD === 'chrome' && cfg.GOOGLE_CLIENT_ID) {
  manifest.oauth2 = { client_id: cfg.GOOGLE_CLIENT_ID, scopes: ['https://www.googleapis.com/auth/drive.readonly'] };
} else {
  delete manifest.oauth2;
}
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

console.log('Wrote extension/config.js:');
for (const [k, v] of Object.entries(cfg)) console.log(`  ${k.padEnd(20)} ${v ? (k.includes('SECRET') ? '****' : v) : '(empty)'}`);
const oauthReady = cfg.GITHUB_CLIENT_ID && (cfg.GITHUB_AUTH_METHOD === 'device' || cfg.TOKEN_EXCHANGE_URL || cfg.GITHUB_CLIENT_SECRET);
if (!cfg.GITHUB_CLIENT_ID) {
  console.log('\n  GitHub sign-in not configured → popup shows the publisher setup screen.');
} else if (!oauthReady) {
  console.log('\n  GITHUB_CLIENT_ID is set but there is no way to finish the token exchange:');
  console.log('  GitHub requires the client secret, so deploy backend/worker.js and pass --token-exchange-url');
  console.log('  (or --github-client-secret for a personal build, or --github-auth-method device).');
} else if (cfg.GITHUB_CLIENT_SECRET && !cfg.TOKEN_EXCHANGE_URL) {
  console.log('\n  WARNING: the client secret is baked into config.js — fine for your own machine, never distribute this build.');
} else {
  console.log(`\n  End users will see: Connect GitHub → GitHub Authorize page → Connected as @username. (${cfg.GITHUB_AUTH_METHOD === 'device' ? 'device flow' : 'exchange via ' + cfg.TOKEN_EXCHANGE_URL})`);
}
if (!cfg.GOOGLE_CLIENT_ID) console.log('  Google Drive disabled → syncing will fail until GOOGLE_CLIENT_ID is set.');
